title: Agro Fund One

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: assets/css/_sass

collections:
  news:
    output: false

exclude: [README.md]

# data for privacy policy
address:
  name: Agro Fund One, Limited
  street: "321 Park Ave"
  city: Wilmette
  state: Illinois
  zip: 60091
  country: United States
  phone: +1 (303) 835-7901
