[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = false
  query = {path = ":path"} #  apply this rule for /old-path?path=example
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/es"
  status = 302
  force = false
  query = {path = ":path"} #  apply this rule for /old-path?path=example
  conditions = {Language = ["es"]}